#обновление данных c node-exporter каждые 15с
global:
  scrape_interval:     15s

scrape_configs:

  # Так как node-exporter на хосте,
  # задаем обращение к нему как 'host.docker.internal:9100'
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
