version: '3'

#побщие параметры сети контейнеров
networks:
  mynetwork:
    ipam:
      config:
      - subnet: 172.16.1.0/24


services:

  ngx:
    container_name: ngx
    image: nginx:latest
    #запускать после сервера Apache
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      #монтируем файл конфигурации, нужный для настройки reverse-proxy
      - ./srv/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      #выводим логи
      - ./srv/nginx/logs:/var/log/nginx
    #перезагрузка контейнера при ошибке
    restart: always
    #настройка IP контейнера Nginx
    networks:
      mynetwork:
        ipv4_address: 172.16.1.3

  web:
    container_name: web
    image: jlekowski/php7.2-apache-mysqli
    #запускать после баз данных
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      #монтируем папку с сайтами 
      - ./srv/www:/var/www
      #сюда кладем конфиги сайтов
      - ./srv/apache2/conf/sites-available:/etc/apache2/sites-available
      #сюда создаем ссылки ln для активации сайтов
      - ./srv/apache2/conf/sites-enabled:/etc/apache2/sites-enabled
      #конфигурации Apache
      - ./srv/apache2/conf/ports.conf:/etc/apache2/ports.conf
      - ./srv/apache2/conf/apache2.conf:/etc/apache2/apache2.conf
      #логи
      - ./srv/apache2/logs:/var/log/apache2
    #перезагрузка контейнера при ошибке
    restart: always
    #настройка IP контейнера Apache
    networks:
      mynetwork:
        ipv4_address: 172.16.1.4

  db:
    container_name: db
    image: mysql
    environment:
    #настройки авторизации для БД
      - MYSQL_ROOT_PASSWORD=rootdb
      - MYSQL_DATABASE=MYDB
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser
    ports:
        - "3306:3306"
    volumes:
      # конфиг Mysql, важно раскомментить default-authentication-plugin=mysql_native_password (https://www.php.net/manual/ru/mysqli.requirements.php)
      - ./srv/mysql/conf/my.cnf:/etc/my.cnf 
      # монтируем директорию с базами данных внутрь контейнера
      - ./srv/mysql/data/:/var/lib/mysql/
      # монтируем директорию с логами MySQL внутрь контейнера
      - ./srv/mysql/logs/:/var/log/mysql/
    #перезагрузка при изменении конфигурации
    restart: always
    #настройка IP контейнера MySql
    networks:
      mynetwork:
        ipv4_address: 172.16.1.5

